/*
==========================================================
 Blinkit Business Analytics
 SQL Business Analysis
 Author : Sujal Tamboli
==========================================================
*/

-- ========================================================
-- SECTION 1 : BUSINESS KPIs
-- ========================================================

-- Q1. Find the total number of customers.
SELECT COUNT(*) AS total_customers
FROM customers;


-- Q2. Find the total number of products.
SELECT COUNT(*) AS total_products
FROM products;


-- Q3. Find the total number of orders.
SELECT COUNT(*) AS total_orders
FROM orders;


-- Q4. Find the total revenue generated from all orders.
SELECT ROUND(SUM(order_total), 2) AS total_revenue
FROM orders;


-- Q5. Calculate the Average Order Value (AOV).
SELECT ROUND(AVG(order_total), 2) AS aov
FROM orders;


-- Q6. Find the highest order value.
SELECT MAX(order_total) AS highest_order_value
FROM orders;


-- Q7. Find the lowest order value.
SELECT MIN(order_total) AS lowest_order_value
FROM orders;


-- Q8. Calculate the total marketing spend.
SELECT ROUND(SUM(spend), 2) AS total_marketing_spend
FROM marketing_performance;


-- Q9. Calculate the total revenue generated by marketing campaigns.
SELECT ROUND(SUM(revenue_generated), 2) AS total_revenue_generated
FROM marketing_performance;


-- Q10. Calculate the overall ROAS.
SELECT ROUND(SUM(revenue_generated) / SUM(spend), 2) AS roas
FROM marketing_performance;


-- ========================================================
-- SECTION 2 : CUSTOMER ANALYSIS
-- ========================================================

-- Q11. Find the top 10 customers by total spending.
SELECT
    c.customer_id,
    c.customer_name,
    SUM(o.order_total) AS total_spent
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_spent DESC
LIMIT 10;


-- Q12. Find the top 10 customers by number of orders.
SELECT
    c.customer_id,
    c.customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_orders DESC
LIMIT 10;


-- Q13. Find the top 10 customers with the highest average order value.
SELECT
    c.customer_id,
    c.customer_name,
    ROUND(AVG(o.order_total), 2) AS average_order_value
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY average_order_value DESC
LIMIT 10;


-- Q14. Find the number of customers who have placed at least one order.
SELECT COUNT(DISTINCT c.customer_id) AS customers_with_orders
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.order_id IS NOT NULL;


-- Q15. Find the number of customers who have never placed an order.
SELECT COUNT(DISTINCT c.customer_id) AS customers_without_orders
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;


-- Q16. Find the percentage of customers who have placed at least one order.
SELECT
    ROUND(
        (customer_with_orders / total_customers) * 100,
        2
    ) AS customer_order_rate
FROM (
    SELECT
        COUNT(DISTINCT CASE
            WHEN o.order_id IS NOT NULL THEN c.customer_id
        END) AS customer_with_orders,
        COUNT(DISTINCT c.customer_id) AS total_customers
    FROM customers c
    LEFT JOIN orders o
        ON c.customer_id = o.customer_id
) AS customer_stats;


-- Q17. Classify customers into High, Medium, and Low value segments.
SELECT
    c.customer_id,
    c.customer_name,
    SUM(o.order_total) AS total_spent,
    CASE
        WHEN SUM(o.order_total) >= 10000 THEN 'High Value'
        WHEN SUM(o.order_total) BETWEEN 5000 AND 9999 THEN 'Medium Value'
        ELSE 'Low Value'
    END AS customer_value_segment
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name;


-- ========================================================
-- SECTION 3 : PRODUCT ANALYSIS
-- ========================================================

-- Q18. Find the top 5 product categories by total revenue.
SELECT
    p.category,
    ROUND(SUM(o.quantity * o.unit_price), 2) AS total_revenue
FROM products p
LEFT JOIN order_items o
    ON p.product_id = o.product_id
GROUP BY p.category
ORDER BY total_revenue DESC
LIMIT 5;


-- Q19. Find the top 10 best-selling products by total quantity sold.
SELECT
    p.product_id,
    p.product_name,
    SUM(o.quantity) AS total_quantity_sold
FROM products p
LEFT JOIN order_items o
    ON p.product_id = o.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_quantity_sold DESC
LIMIT 10;


-- Q20. Find the average selling price of each product.
SELECT
    p.product_id,
    p.product_name,
    ROUND(AVG(o.unit_price), 2) AS average_selling_price
FROM products p
LEFT JOIN order_items o
    ON p.product_id = o.product_id
GROUP BY p.product_id, p.product_name
ORDER BY average_selling_price DESC;


-- Q21. Find the top 10 products with the highest total revenue.
SELECT
    p.product_id,
    p.product_name,
    ROUND(SUM(o.quantity * o.unit_price), 2) AS total_revenue
FROM products p
LEFT JOIN order_items o
    ON p.product_id = o.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_revenue DESC
LIMIT 10;


-- Q22. Find the top 5 product categories by total quantity sold.
SELECT
    p.category,
    SUM(o.quantity) AS total_quantity_sold
FROM products p
LEFT JOIN order_items o
    ON p.product_id = o.product_id
GROUP BY p.category
ORDER BY total_quantity_sold DESC
LIMIT 5;


-- Q23. Find the top 10 products with the highest average revenue per order item.
SELECT
    p.product_id,
    p.product_name,
    ROUND(AVG(o.quantity * o.unit_price), 2) AS average_item_revenue
FROM products p
LEFT JOIN order_items o
    ON p.product_id = o.product_id
GROUP BY p.product_id, p.product_name
ORDER BY average_item_revenue DESC
LIMIT 10;


-- Q24. Find the product with the highest single-item revenue.
SELECT
    p.product_id,
    p.product_name,
    ROUND(MAX(o.quantity * o.unit_price), 2) AS item_revenue
FROM products p
LEFT JOIN order_items o
    ON p.product_id = o.product_id
GROUP BY p.product_id, p.product_name
ORDER BY item_revenue DESC
LIMIT 1;


-- Q25. Find the total revenue contribution percentage of each product category.
SELECT
    p.category,
    ROUND(SUM(o.quantity * o.unit_price), 2) AS category_revenue,
    ROUND(
        (
            SUM(o.quantity * o.unit_price)
            / (SELECT SUM(quantity * unit_price) FROM order_items)
        ) * 100,
        2
    ) AS revenue_percentage
FROM products p
LEFT JOIN order_items o
    ON p.product_id = o.product_id
GROUP BY p.category
ORDER BY revenue_percentage DESC;


-- Q26. Find the top 10 products with the highest revenue per unit sold.
SELECT
    p.product_id,
    p.product_name,
    ROUND(
        SUM(o.quantity * o.unit_price) / SUM(o.quantity),
        2
    ) AS revenue_per_unit
FROM products p
LEFT JOIN order_items o
    ON p.product_id = o.product_id
GROUP BY p.product_id, p.product_name
ORDER BY revenue_per_unit DESC
LIMIT 10;


-- Q27. Find the top 5 brands by total revenue.
SELECT
    p.brand,
    ROUND(SUM(o.quantity * o.unit_price), 2) AS total_revenue
FROM products p
LEFT JOIN order_items o
    ON p.product_id = o.product_id
GROUP BY p.brand
ORDER BY total_revenue DESC
LIMIT 5;


-- Q28. Find the top 5 brands by total quantity sold.
SELECT
    p.brand,
    SUM(o.quantity) AS total_quantity_sold
FROM products p
LEFT JOIN order_items o
    ON p.product_id = o.product_id
GROUP BY p.brand
ORDER BY total_quantity_sold DESC
LIMIT 5;


-- Q29. Find the top 10 products with the highest total profit.
SELECT
    p.product_id,
    p.product_name,
    ROUND(
        SUM(
            o.quantity
            * o.unit_price
            * (p.margin_percentage / 100)
        ),
        2
    ) AS total_profit
FROM products p
LEFT JOIN order_items o
    ON p.product_id = o.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_profit DESC
LIMIT 10;


-- Q30. Find the top 5 product categories by total profit.
SELECT
    p.category,
    ROUND(
        SUM(
            o.quantity
            * o.unit_price
            * (p.margin_percentage / 100)
        ),
        2
    ) AS total_profit
FROM products p
LEFT JOIN order_items o
    ON p.product_id = o.product_id
GROUP BY p.category
ORDER BY total_profit DESC
LIMIT 5;


-- Q31. Find the top 10 products by profit margin percentage.
SELECT
    p.product_id,
    p.product_name,
    p.margin_percentage
FROM products p
ORDER BY p.margin_percentage DESC
LIMIT 10;


-- Q32. Rank each product within its category based on total revenue.
WITH product_revenue AS (
    SELECT
        p.product_id,
        p.product_name,
        p.category,
        ROUND(SUM(o.quantity * o.unit_price), 2) AS total_revenue
    FROM products p
    LEFT JOIN order_items o
        ON p.product_id = o.product_id
    GROUP BY p.product_id, p.product_name, p.category
)
SELECT
    product_id,
    product_name,
    category,
    total_revenue,
    RANK() OVER (
        PARTITION BY category
        ORDER BY total_revenue DESC
    ) AS category_rank
FROM product_revenue
ORDER BY category, category_rank;


-- Q33. Find the top 3 products in each category based on total revenue.
WITH product_revenue AS (
    SELECT
        p.product_id,
        p.product_name,
        p.category,
        ROUND(SUM(o.quantity * o.unit_price), 2) AS total_revenue
    FROM products p
    LEFT JOIN order_items o
        ON p.product_id = o.product_id
    GROUP BY p.product_id, p.product_name, p.category
),
ranked_products AS (
    SELECT
        product_id,
        product_name,
        category,
        total_revenue,
        RANK() OVER (
            PARTITION BY category
            ORDER BY total_revenue DESC
        ) AS category_rank
    FROM product_revenue
)
SELECT
    product_id,
    product_name,
    category,
    total_revenue,
    category_rank
FROM ranked_products
WHERE category_rank <= 3
ORDER BY category, category_rank;


-- Q34. Find the percentage of products that have been sold at least once.
SELECT
    ROUND(
        (
            COUNT(DISTINCT o.product_id)
            / COUNT(DISTINCT p.product_id)
        ) * 100,
        2
    ) AS products_sold_percentage
FROM products p
LEFT JOIN order_items o
    ON p.product_id = o.product_id;


-- Q35. Find the average revenue generated per product category.
WITH category_revenue AS (
    SELECT
        p.category,
        SUM(o.quantity * o.unit_price) AS total_revenue
    FROM products p
    LEFT JOIN order_items o
        ON p.product_id = o.product_id
    GROUP BY p.category
)
SELECT
    ROUND(AVG(total_revenue), 2) AS average_category_revenue
FROM category_revenue;


-- ========================================================
-- SECTION 4 : SALES ANALYSIS
-- ========================================================

-- Q36. Find the total revenue generated for each month.
SELECT
    DATE_FORMAT(order_date, '%Y-%m') AS month,
    ROUND(SUM(order_total), 2) AS total_revenue
FROM orders
GROUP BY DATE_FORMAT(order_date, '%Y-%m')
ORDER BY month;


-- Q37. Find the total number of orders and total revenue for each month.
SELECT
    DATE_FORMAT(order_date, '%Y-%m') AS month,
    COUNT(order_id) AS total_orders,
    ROUND(SUM(order_total), 2) AS total_revenue
FROM orders
GROUP BY DATE_FORMAT(order_date, '%Y-%m')
ORDER BY month;


-- Q38. Find the month with the highest total revenue.
SELECT
    DATE_FORMAT(order_date, '%Y-%m') AS month,
    ROUND(SUM(order_total), 2) AS total_revenue
FROM orders
GROUP BY DATE_FORMAT(order_date, '%Y-%m')
ORDER BY total_revenue DESC
LIMIT 1;


-- Q39. Find the month with the highest number of orders.
SELECT
    DATE_FORMAT(order_date, '%Y-%m') AS month,
    COUNT(order_id) AS total_orders
FROM orders
GROUP BY DATE_FORMAT(order_date, '%Y-%m')
ORDER BY total_orders DESC
LIMIT 1;


-- Q40. Find the average order value for each month.
SELECT
    DATE_FORMAT(order_date, '%Y-%m') AS month,
    ROUND(AVG(order_total), 2) AS average_order_value
FROM orders
GROUP BY DATE_FORMAT(order_date, '%Y-%m')
ORDER BY month;


-- Q41. Find month-over-month revenue growth.
WITH monthly_sales AS (
    SELECT
        DATE_FORMAT(order_date, '%Y-%m') AS month,
        SUM(order_total) AS total_revenue
    FROM orders
    GROUP BY DATE_FORMAT(order_date, '%Y-%m')
),
monthly_growth AS (
    SELECT
        month,
        total_revenue,
        LAG(total_revenue) OVER (
            ORDER BY month
        ) AS previous_month_revenue
    FROM monthly_sales
)
SELECT
    month,
    ROUND(total_revenue, 2) AS total_revenue,
    ROUND(previous_month_revenue, 2) AS previous_month_revenue,
    ROUND(
        (
            (total_revenue - previous_month_revenue)
            / previous_month_revenue
        ) * 100,
        2
    ) AS revenue_growth_percentage
FROM monthly_growth
ORDER BY month;


-- Q42. Find the month with the highest revenue growth percentage.
WITH monthly_sales AS (
    SELECT
        DATE_FORMAT(order_date, '%Y-%m') AS month,
        SUM(order_total) AS total_revenue
    FROM orders
    GROUP BY DATE_FORMAT(order_date, '%Y-%m')
),
monthly_lag AS (
    SELECT
        month,
        total_revenue,
        LAG(total_revenue) OVER (
            ORDER BY month
        ) AS previous_month_revenue
    FROM monthly_sales
),
revenue_growth AS (
    SELECT
        month,
        ROUND(
            (
                (total_revenue - previous_month_revenue)
                / previous_month_revenue
            ) * 100,
            2
        ) AS revenue_growth_percentage
    FROM monthly_lag
    WHERE previous_month_revenue IS NOT NULL
)
SELECT
    month,
    revenue_growth_percentage
FROM revenue_growth
ORDER BY revenue_growth_percentage DESC
LIMIT 1;


-- Q43. Find the month with the lowest revenue growth percentage.
WITH monthly_sales AS (
    SELECT
        DATE_FORMAT(order_date, '%Y-%m') AS month,
        SUM(order_total) AS total_revenue
    FROM orders
    GROUP BY DATE_FORMAT(order_date, '%Y-%m')
),
monthly_lag AS (
    SELECT
        month,
        total_revenue,
        LAG(total_revenue) OVER (
            ORDER BY month
        ) AS previous_month_revenue
    FROM monthly_sales
),
revenue_growth AS (
    SELECT
        month,
        ROUND(
            (
                (total_revenue - previous_month_revenue)
                / previous_month_revenue
            ) * 100,
            2
        ) AS revenue_growth_percentage
    FROM monthly_lag
    WHERE previous_month_revenue IS NOT NULL
)
SELECT
    month,
    revenue_growth_percentage
FROM revenue_growth
ORDER BY revenue_growth_percentage ASC
LIMIT 1;


-- Q44. Find the average monthly revenue across the entire period.
WITH monthly_revenue AS (
    SELECT
        DATE_FORMAT(order_date, '%Y-%m') AS month,
        SUM(order_total) AS total_revenue
    FROM orders
    GROUP BY DATE_FORMAT(order_date, '%Y-%m')
)
SELECT
    ROUND(AVG(total_revenue), 2) AS average_monthly_revenue
FROM monthly_revenue;


-- Q45. Find the month with the highest Average Order Value (AOV).
WITH monthly_aov AS (
    SELECT
        DATE_FORMAT(order_date, '%Y-%m') AS month,
        ROUND(AVG(order_total), 2) AS average_order_value
    FROM orders
    GROUP BY DATE_FORMAT(order_date, '%Y-%m')
)
SELECT
    month,
    average_order_value
FROM monthly_aov
ORDER BY average_order_value DESC
LIMIT 1;


-- Q46. Find the percentage of total revenue generated by each month.
WITH monthly_revenue AS (
    SELECT
        DATE_FORMAT(order_date, '%Y-%m') AS month,
        SUM(order_total) AS total_revenue
    FROM orders
    GROUP BY DATE_FORMAT(order_date, '%Y-%m')
)
SELECT
    month,
    ROUND(total_revenue, 2) AS total_revenue,
    ROUND(
        (
            total_revenue
            / (SELECT SUM(order_total) FROM orders)
        ) * 100,
        2
    ) AS revenue_percentage
FROM monthly_revenue
ORDER BY revenue_percentage DESC;


-- Q47. Find the cumulative (running) revenue by month.
WITH monthly_revenue AS (
    SELECT
        DATE_FORMAT(order_date, '%Y-%m') AS month,
        SUM(order_total) AS monthly_revenue
    FROM orders
    GROUP BY DATE_FORMAT(order_date, '%Y-%m')
)
SELECT
    month,
    ROUND(monthly_revenue, 2) AS monthly_revenue,
    ROUND(
        SUM(monthly_revenue) OVER (
            ORDER BY month
        ),
        2
    ) AS cumulative_revenue
FROM monthly_revenue
ORDER BY month;


-- Q48. Find the first month in which cumulative revenue exceeded 50% of total revenue.
WITH monthly_revenue AS (
    SELECT
        DATE_FORMAT(order_date, '%Y-%m') AS month,
        SUM(order_total) AS monthly_revenue
    FROM orders
    GROUP BY DATE_FORMAT(order_date, '%Y-%m')
),
cumulative_sales AS (
    SELECT
        month,
        monthly_revenue,
        SUM(monthly_revenue) OVER (
            ORDER BY month
        ) AS cumulative_revenue
    FROM monthly_revenue
),
revenue_percentage AS (
    SELECT
        month,
        cumulative_revenue,
        ROUND(
            (
                cumulative_revenue
                / (SELECT SUM(order_total) FROM orders)
            ) * 100,
            2
        ) AS total_revenue_percentage
    FROM cumulative_sales
)
SELECT
    month,
    ROUND(cumulative_revenue, 2) AS cumulative_revenue,
    total_revenue_percentage
FROM revenue_percentage
WHERE total_revenue_percentage > 50
ORDER BY month
LIMIT 1;


-- Q49. Find the month with the highest number of unique customers.
SELECT
    DATE_FORMAT(order_date, '%Y-%m') AS month,
    COUNT(DISTINCT customer_id) AS unique_customers
FROM orders
GROUP BY DATE_FORMAT(order_date, '%Y-%m')
ORDER BY unique_customers DESC
LIMIT 1;


-- Q50. Find the month with the highest number of new customers.
WITH first_customer_order AS (
    SELECT
        customer_id,
        MIN(order_date) AS first_order_date
    FROM orders
    GROUP BY customer_id
)
SELECT
    DATE_FORMAT(first_order_date, '%Y-%m') AS month,
    COUNT(customer_id) AS new_customers
FROM first_customer_order
GROUP BY DATE_FORMAT(first_order_date, '%Y-%m')
ORDER BY new_customers DESC
LIMIT 1;


-- ========================================================
-- SECTION 5 : DELIVERY ANALYSIS
-- ========================================================

-- Q51. Find the average delivery time for each delivery status.
SELECT
    delivery_status,
    ROUND(AVG(delivery_time_minutes), 2) AS avg_delivery_time_minutes
FROM delivery_performance
GROUP BY delivery_status
ORDER BY avg_delivery_time_minutes DESC;


-- Q52. Find the percentage of orders that were delivered late.
-- Delayed statuses in this dataset:
-- Slightly Delayed and Significantly Delayed.
SELECT
    ROUND(
        (
            COUNT(
                CASE
                    WHEN delivery_status IN (
                        'Slightly Delayed',
                        'Significantly Delayed'
                    )
                    THEN 1
                END
            ) / COUNT(*)
        ) * 100,
        2
    ) AS late_delivery_percentage
FROM delivery_performance;


-- Q53. Find the top 5 delivery partners with the highest average delivery time.
SELECT
    delivery_partner_id,
    ROUND(AVG(delivery_time_minutes), 2) AS average_delivery_time_minutes
FROM delivery_performance
GROUP BY delivery_partner_id
ORDER BY average_delivery_time_minutes DESC
LIMIT 5;


-- Q54. Find the top 5 delivery partners with the highest number of delayed orders.
SELECT
    delivery_partner_id,
    COUNT(
        CASE
            WHEN delivery_status IN (
                'Slightly Delayed',
                'Significantly Delayed'
            )
            THEN 1
        END
    ) AS delayed_orders
FROM delivery_performance
GROUP BY delivery_partner_id
ORDER BY delayed_orders DESC
LIMIT 5;


-- ========================================================
-- SECTION 6 : INVENTORY ANALYSIS
-- ========================================================

-- Q55. Find the top 5 products with the highest damaged stock.
SELECT
    p.product_id,
    p.product_name,
    SUM(i.damaged_stock) AS total_damaged_stock
FROM products p
LEFT JOIN inventory i
    ON p.product_id = i.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_damaged_stock DESC
LIMIT 5;


-- Q56. Find the top 5 products with the highest total stock received.
SELECT
    p.product_id,
    p.product_name,
    SUM(i.stock_received) AS total_stock_received
FROM products p
LEFT JOIN inventory i
    ON p.product_id = i.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_stock_received DESC
LIMIT 5;


-- Q57. Find the top 5 products with the highest damage rate.
SELECT
    p.product_id,
    p.product_name,
    ROUND(
        (
            SUM(i.damaged_stock)
            / NULLIF(SUM(i.stock_received), 0)
        ) * 100,
        2
    ) AS damage_rate_percentage
FROM products p
LEFT JOIN inventory i
    ON p.product_id = i.product_id
GROUP BY p.product_id, p.product_name
ORDER BY damage_rate_percentage DESC
LIMIT 5;


-- ========================================================
-- SECTION 7 : CUSTOMER FEEDBACK ANALYSIS
-- ========================================================

-- Q58. Find the average customer rating for each feedback category.
SELECT
    feedback_category,
    ROUND(AVG(rating), 2) AS average_rating
FROM customer_feedback
GROUP BY feedback_category
ORDER BY average_rating DESC;


-- Q59. Find the percentage of feedback that is positive, negative, and neutral.
SELECT
    sentiment,
    ROUND(
        (
            COUNT(*) / (SELECT COUNT(*) FROM customer_feedback)
        ) * 100,
        2
    ) AS feedback_percentage
FROM customer_feedback
GROUP BY sentiment
ORDER BY feedback_percentage DESC;


-- Q60. Find the top 5 customers with the lowest average ratings.
SELECT
    c.customer_id,
    c.customer_name,
    ROUND(AVG(f.rating), 2) AS average_rating
FROM customers c
LEFT JOIN customer_feedback f
    ON c.customer_id = f.customer_id
WHERE f.rating IS NOT NULL
GROUP BY c.customer_id, c.customer_name
ORDER BY average_rating ASC
LIMIT 5;


-- ========================================================
-- END OF SQL BUSINESS ANALYSIS
-- 60 BUSINESS QUESTIONS COMPLETED
-- ========================================================