/*==========================================================
 Blinkit Business Analytics
 SQL Business Analysis
 Author : Sujal Tamboli
==========================================================*/


/*==========================================================
SECTION 1 : BUSINESS KPIs
==========================================================*/


-- Q1. Find the total number of customers.

select count(*) as total_customers 
from customers ;


-- Q2. Find the total number of products in the products table.


select count(*) as total_products
from products;



--Q3. Find the total number of orders in the orders table.

select count(*) as total_orders 
from orders;


-- Calculate the total revenue generated from all orders using the order_total column.

select round(sum(order_total),2) as total_revenue
from orders;


-- Calculate the Average Order Value (AOV) using order_total.

select round(avg(order_total),2) as aov
from orders;

-- Find the highest order value from the orders table.

select max(order_total) as highest_order_value from orders ;

-- Find the lowest order value from the orders table.

select min(order_total) as lowest_order_value from orders;

-- Calculate the total marketing spend from the marketing_performance table using the spend column.

select round(sum(spend),2) as total_marketing_spend from marketing_performance;

-- Calculate the total revenue generated from all marketing campaigns using the revenue_generated column.

select round(sum(revenue_generated),2) as total_revenue_generated from marketing_performance ;

-- Calculate the overall ROAS (Return on Ad Spend) using total revenue_generated divided by total spend.

select round(sum(revenue_generated) / sum(spend),2) as roas from marketing_performance;


/*==========================================================
SECTION 2 : CUSTOMER ANALYSIS
==========================================================*/


-- Find the top 10 customers by total spending. Return:

-- customer_id
-- customer_name
-- total_spent

-- Sort from highest to lowest spending.

select 
    c.customer_id ,
    c.customer_name ,
    sum(o.order_total) as total_spend
from customers c 
left join orders o 
on c.customer_id =  o.customer_id
group by customer_id
order by total_spend desc
limit 10;


-- Find the top 10 customers by number of orders.

-- Return:

-- customer_id
-- customer_name
-- total_orders

-- Sort from highest number of orders to lowest.


select 
    c.customer_id,
    c.customer_name,
    count(o.order_id) as total_orders
from 
    customers c
left join 
    orders o 
on  
    c.customer_id = o.customer_id
group by c.customer_id , c.customer_name 
order by total_orders desc
limit 10 


-- Find the average order value for each customer.

-- Return:

-- customer_id
-- customer_name
-- average_order_value

-- Show the top 10 customers with the highest average order value.


select 
    c.customer_id ,
    c.customer_name ,
    ROUND(AVG(o.order_total), 2) as average_order_value
from 
    customers c 
left join 
    orders o 
on 
    c.customer_id = o.customer_id
group by c.customer_id , c.customer_name 
order by average_order_value desc
limit 10;


-- Find the number of customers who have placed at least one order.

-- Return the result as:

-- customers_with_orders

select count(distinct c.customer_id) as customers_with_orders
from customers c 
left join orders o 
on c.customer_id = o.customer_id
where o.order_id is not null


-- Q15

-- Find the number of customers who have never placed an order.

-- Return:

-- customers_without_orders

select count(distinct c.customer_id) as customers_without_orders
from customers c 
left join orders o 
on c.customer_id = o.customer_id
where o.order_id is null


-- Find the percentage of customers who have placed at least one order.

-- Return:

-- customer_order_rate as a percentage rounded to 2 decimal places.


select 
    round(
        (customer_with_orders/ total_customers) *100
        ,2
    ) as customer_order_rate 
from 
    (
        SELECT
            COUNT(DISTINCT CASE
                WHEN o.order_id IS NOT NULL THEN c.customer_id
            END) AS customer_with_orders,
        
            COUNT(DISTINCT c.customer_id) AS total_customers
        
        FROM customers c
        LEFT JOIN orders o
            ON c.customer_id = o.customer_id
        
    ) as customer_stats



--  Find the total revenue generated by each customer and classify customers into:

-- High Value → total spending ≥ 10,000
-- Medium Value → total spending between 5,000 and 9,999
-- Low Value → total spending < 5,000

-- Return:

-- customer_id
-- customer_name
-- total_spent
-- customer_value_segment


select 
    c.customer_id,
    c.customer_name,
    sum(o.order_total) as total_spent,
    case 
        when sum(o.order_total) >= 10000 then 'high value'
        when sum(o.order_total) between 5000 and 9999 then 'medium value'
        else 'low value'
        end as customer_value_segment
from 
    customers c
left join 
    orders o 
on c.customer_id = o.customer_id
group by c.customer_id, c.customer_name



-- Find the top 5 product categories that generated the highest revenue.

-- Return:

-- category
-- total_revenue

-- Requirements:

-- Use the appropriate JOIN
-- Use SUM()
-- Use GROUP BY
-- Sort by revenue in descending order
-- Return only the top 5 categories 

select 
    p.category,
    round(sum(quantity * unit_price),2) as total_revenue 
from 
    products p
left join 
    order_items o 
on p.product_id = o.product_id
group by p.category
order by total_revenue desc
limit 5


/*==========================================================
SECTION 3 : PRODUCT ANALYSIS
==========================================================*/


-- Management wants to identify the Top 10 best-selling products based on the total quantity sold.

-- Return:
-- product_id
-- product_name
-- total_quantity_sold

select 
    p.product_id,
    p.product_name,
    sum(o.quantity) as total_quantity_sold
from
    products p
left join 
    order_items o
on 
    p.product_id = o.product_id   
group by p.product_id , p.product_name 
order by total_quantity_sold desc  
limit 10 


-- Find the average selling price of each product.

-- Return:

-- product_id
-- product_name
-- average_selling_price


select 
    p.product_id,
    p.product_name,
    round(avg(o.unit_price),2) as average_selling_price
from 
    products p 
left join 
    order_items o 
on 
    p.product_id = o.product_id
group by p.product_id , p.product_name



-- Q21

-- Find the top 10 products with the highest total revenue.

-- Return:

-- product_id
-- product_name
-- total_revenue

-- Use order_items to calculate revenue as quantity × unit_price.


select 
    p.product_id,
    p.product_name,
    round(sum(o.quantity * o.unit_price),2) as total_revenue
from 
    products p 
left join 
    order_items o
on 
    p.product_id = o.product_id
group by p.product_id , p.product_name 
order by total_revenue desc
limit 10


-- Q22

-- Find the top 5 product categories by total quantity sold.

-- Return:

-- category
-- total_quantity_sold

-- Use products and order_items, and sort from highest to lowest.


select 
    p.category,
    sum(o.quantity) as total_quantity_sold
from 
    products p 
left join 
    order_items o
on 
    p.product_id = o.product_id
group by p.category 
order by total_quantity_sold desc
limit 5


-- Q23

-- Find the top 10 products with the highest average revenue per order item.

-- Return:

-- product_id
-- product_name
-- average_item_revenue

-- Calculate item revenue as:

-- quantity × unit_price

-- Then calculate the average for each product.

-- Sort from highest to lowest and return only the top 10.


select 
    p.product_id,
    p.product_name ,
    round(avg(o.quantity * o.unit_price),2) as average_item_revenue
from
    products p 
left join 
    order_items o 
on  
    p.product_id = o.product_id 
group by 
    p.product_id , p.product_name
order by 
    average_item_revenue desc
limit
    10

--     Q24: Find the product with the highest single-item revenue.

-- Return:

-- product_id
-- product_name
-- item_revenue

-- Calculate item_revenue as quantity × unit_price.

select 
    p.product_id,
    p.product_name,
    round(max(o.quantity * o.unit_price),2) as item_revenue 
from
    products p
left join 
    order_items o
on 
    p.product_id = o.product_id 
group by 
    p.product_id,p.product_name
order by 
    item_revenue desc
limit
    1


--     Find the total revenue contribution percentage of each product category.

-- Return:

-- category
-- category_revenue
-- revenue_percentage


select 
    p.category,
    round(sum(o.quantity * o.unit_price),2) as category_revenue,
    round(sum(o.quantity * o.unit_price)/(select sum(quantity * unit_price) from order_items) * 100,2) as revenue_percentage
from
    products p
left join 
    order_items o
on 
    p.product_id = o.product_id 
group by 
    p.category
order by 
    revenue_percentage desc


-- Find the top 10 products with the highest revenue per unit sold.

-- Return:

-- product_id
-- product_name
-- revenue_per_unit

select 
    p.product_id ,
    p.product_name,
    round(sum(o.quantity * o.unit_price)/ sum(o.quantity),2) as revenue_per_unit
from
    products p 
left join 
    order_items o 
on 
    p.product_id = o.product_id 
group by p.product_id , p.product_name 
order by revenue_per_unit desc
limit 10


-- Q27

-- Find the top 5 brands by total revenue.

-- Return:

-- brand
-- total_revenue

-- Use products and order_items.

-- Calculate revenue as:

-- quantity × unit_price

-- Sort by total_revenue descending.


select 
    p.brand,
    round(sum(o.quantity * o.unit_price),2) as total_revenue
from 
    products p 
left join 
    order_Items o 
on 
    p.product_id = o.product_id 
group by p.brand 
order by total_revenue desc
limit 5


-- Find the top 5 brands by total quantity sold.

-- Return:
-- brand
-- total_quantity_sold

select 
    p.brand,
    round(sum(o.quantity)) as total_quantity_sold
from   
    products p
left join 
    order_items o
on 
    p.product_id = o.product_id
group by p.brand
order by total_quantity_sold desc
limit 5

-- Find the top 10 products with the highest total profit.

-- Return:

-- product_id
-- product_name
-- total_profit

-- Use the product's margin percentage and sales data to calculate profit


select 
    p.product_id,
    p.product_name,
    sum(o.quantity * o.unit_price * (p.margin_percentage / 100)) as total_profit
from 
    products p
left join 
    order_items o
on 
    p.product_id = o.product_id
group by p.product_id , p.product_name
order by total_profit desc
limit 10


-- Find the top 5 product categories by total profit.

-- Return:

-- category
-- total_profit

select 
    p.category,
    sum(o.quantity * o.unit_price * (p.margin_percentage / 100)) as total_profit
from 
    products p 
left join order_items o
on p.product_id = o.product_id 
group by p.category
order by total_profit desc
limit 5 


-- Q31

-- Find the top 10 products by profit margin percentage.

-- Return:

-- product_id
-- product_name
-- margin_percentage

-- Sort from highest to lowest and return the top 10.


select 
    p.product_id,
    p.product_name,
    p.margin_percentage
from products p
group by p.product_id,p.product_name
order by p.margin_percentage 
limit 10


-- Find the rank of each product within its category based on total revenue.

-- Return:

-- product_id
-- product_name
-- category
-- total_revenue
-- category_rank


with product_revenue as(
select 
    p.product_id,
    p.product_name,
    p.category,
    round(sum(o.quantity * o.unit_price),2) as total_revenue
from
    products p
left join 
    order_items o
on 
    p.product_id = o.product_id
group by 
    p.product_id,
    p.product_name,
    p.category
)

select 
    product_id ,
    product_name,
    category,
    total_revenue,
    rank() over (
        partition by category  
        order by total_revenue desc
    ) as category_rank
from 
    product_revenue
order by category, category_rank


-- Find the top 3 products in each category based on total revenue.

-- Return:

-- product_id
-- product_name
-- category
-- total_revenue
-- category_rank

with product_revenue as(
select              
    p.product_id,
    p.product_name,
    p.category,
    round(sum(o.quantity * o.unit_price),2) as total_revenue
from
    products p
left join
    order_items o
on  
    p.product_id = o.product_id

group by
    p.product_id,
    p.product_name,
    p.category
)

ranked-products as (select 
    product_id,
    product_name,
    category,
    total_revenue,
    rank() over (
        partition by category
        order by total_revenue desc
    ) as category_rank
from
    product_revenue
)

SELECT
    product_id,
    product_name,
    category,
    total_revenue,
    category_rank
FROM ranked_products
WHERE category_rank <= 3
ORDER BY category, category_rank;

-- Find the percentage of products that have been sold at least once.

-- Return:

-- products_sold_percentage

-- Round the result to 2 decimal places.

 SELECT
    ROUND(
        (
            COUNT(DISTINCT o.product_id)
            /
            COUNT(DISTINCT p.product_id)
        ) * 100,
        2
    ) AS products_sold_percentage
FROM products p
LEFT JOIN order_items o
    ON p.product_id = o.product_id;

--     Find the average revenue generated per product category.

-- Return:

-- category
-- average_category_revenue


WITH category_revenue AS (
    SELECT
        p.category,
        ROUND(SUM(o.quantity * o.unit_price), 2) AS total_revenue
    FROM products p
    LEFT JOIN order_items o
        ON p.product_id = o.product_id
    GROUP BY p.category
)

SELECT
    ROUND(AVG(total_revenue), 2) AS average_category_revenue
FROM category_revenue;




/*==========================================================
SECTION 4 : SALES ANALYSIS
==========================================================*/


/*==========================================================
SECTION 5 : DELIVERY ANALYSIS
==========================================================*/


/*==========================================================
SECTION 6 : INVENTORY ANALYSIS
==========================================================*/


/*==========================================================
SECTION 7 : CUSTOMER FEEDBACK
==========================================================*/


/*==========================================================
SECTION 8 : MARKETING ANALYSIS
==========================================================*/